sudo: required

env:
  global:
    - LOCAL_INSTANCE_1_CF_API_URL=https://api.bosh-lite.com
    - LOCAL_INSTANCE_1_username=admin
    - LOCAL_INSTANCE_1_password=admin

language: node_js
node_js:
  - 9.11.0

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sudo bash ./scripts/setup-dnsmasq.sh; fi'

install: npm i

script:
  - npm run lint
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:local; fi'

