environment:
  nodejs_version: "9.11.0"
  LOCAL_INSTANCE_1_CF_API_URL: https://api.bosh-lite.com
  LOCAL_INSTANCE_1_username: admin
  LOCAL_INSTANCE_1_password: admin

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run lint

# Don't actually build.
build: off
